# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 00:24
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: Meetup PythonRio', max_length=90, verbose_name='Nome do Evento')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='nome', unique=True, verbose_name='Slug')),
                ('data', models.DateTimeField(verbose_name='Inicio do Evento')),
                ('local', models.CharField(help_text='Nome da empresa, faculdade, etc... aonde irá acontecer o evento. Ex.: Hotel Urbano.', max_length=90, verbose_name='Local do Evento')),
                ('cidade', models.CharField(max_length=90, verbose_name='Cidade')),
                ('endereco', models.CharField(help_text='Endereço completo do local do evento.', max_length=90, verbose_name='Endereço do Evento')),
                ('sobre', models.TextField(help_text='Sobre o evento, o que vai acontecer, publico alvo, etc...', verbose_name='Descrição do evento')),
                ('inscricoes', models.URLField(verbose_name='URL para as incrições')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name_plural': 'Eventos',
                'verbose_name': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palestras', to='eventos.Evento')),
            ],
            options={
                'verbose_name_plural': 'Palestras',
                'verbose_name': 'Palestra',
            },
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='palestrantes/')),
                ('github', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Palestrantes',
                'verbose_name': 'Palestrante',
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90)),
                ('logo', models.ImageField(upload_to='parceiros/')),
                ('site', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Parceiros',
                'verbose_name': 'Parceiro',
            },
        ),
        migrations.AddField(
            model_name='palestra',
            name='palestrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palestras', to='eventos.Palestrante'),
        ),
        migrations.AddField(
            model_name='evento',
            name='parceiros',
            field=models.ManyToManyField(blank=True, related_name='parceiros', to='eventos.Parceiro'),
        ),
    ]
