# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=90)),
                ('endereco', models.CharField(max_length=90)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('sobre', models.TextField()),
                ('inscricoes', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'verbose_name': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
            options={
                'verbose_name_plural': 'Palestras',
                'verbose_name': 'Palestra',
            },
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('github', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Palestrantes',
                'verbose_name': 'Palestrante',
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
            options={
                'verbose_name_plural': 'Parceiros',
                'verbose_name': 'Parceiro',
            },
        ),
        migrations.AddField(
            model_name='palestra',
            name='palestrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Palestrante'),
        ),
    ]
