# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='latitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default='Some place', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='longitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
