# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cidade',
            field=models.CharField(default='Rio de Janeiro', max_length=90, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(verbose_name='Inicio do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='endereco',
            field=models.CharField(help_text='Endereço completo do local do evento.', max_length=90, verbose_name='Endereço do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inscricoes',
            field=models.URLField(verbose_name='URL para as incrições'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='latitude',
            field=models.IntegerField(blank=True, help_text='Para que o mapa seja exibido na página inicial.', null=True, verbose_name='Latitute'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(help_text='Nome da empresa, faculdade, etc... aonde irá acontecer o evento. Ex.: Hotel Urbano.', max_length=90, verbose_name='Local do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitude',
            field=models.IntegerField(blank=True, help_text='Para que o mapa seja exibido na página inicial.', null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(help_text='Ex.: IV PythonRio', max_length=90, verbose_name='Nome do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='sobre',
            field=models.TextField(help_text='Sobre o evento, o que vai acontecer, publico alvo, etc...', verbose_name='Descrição do evento'),
        ),
    ]
