# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20151205_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('descricao', models.CharField(max_length=255)),
                ('responsavel', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Evento',
            new_name='Edicao',
        ),
        migrations.AddField(
            model_name='programa',
            name='edicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Edicao'),
        ),
    ]
